FROM httpd:alpine

MAINTAINER Garrett
MAINTAINER Nelson
MAINTAINER Steven

RUN echo "Include conf/extra/httpd.conf" >> /usr/local/apache2/conf/httpd.conf

COPY httpd.conf /usr/local/apache2/conf/extra/httpd.conf
